### ISSUE TITLE
java.lang.NoSuchMethodError: java.lang.String com.google.cloud.bigquery.BigQueryOptions.getResolvedApiaryHost(java.lang.String)

### ISSUE THREAD

**Issue by kholisrag** [memiiso/debezium-server-bigquery#195]
Error Logs : 

```log
2024-10-29 13:11:29 debezium-server-bigquery-1  | 2024-10-29 06:11:29,086 INFO  [io.deb.ser.BaseChangeConsumer] (main) Using 'io.debezium.server.BaseChangeConsumer$$Lambda$417/0x00007fff7c3a77f0@d2291de' stream name mapper
2024-10-29 13:11:29 debezium-server-bigquery-1  | 2024-10-29 06:11:29,104 INFO  [io.deb.ser.jso.JsonSerdeConfig] (main) JsonSerdeConfig values: 
2024-10-29 13:11:29 debezium-server-bigquery-1  |       from.field = null
2024-10-29 13:11:29 debezium-server-bigquery-1  |       unknown.properties.ignored = false
2024-10-29 13:11:29 debezium-server-bigquery-1  | 
2024-10-29 13:11:29 debezium-server-bigquery-1  | 2024-10-29 06:11:29,105 INFO  [io.deb.ser.jso.JsonSerdeConfig] (main) JsonSerdeConfig values: 
2024-10-29 13:11:29 debezium-server-bigquery-1  |       from.field = null
2024-10-29 13:11:29 debezium-server-bigquery-1  |       unknown.properties.ignored = false
2024-10-29 13:11:29 debezium-server-bigquery-1  | 
2024-10-29 13:11:29 debezium-server-bigquery-1  | 2024-10-29 06:11:29,111 INFO  [io.deb.ser.big.ConsumerUtil] (main) Using io.quarkus.arc.impl.InstanceImpl
2024-10-29 13:11:29 debezium-server-bigquery-1  | 2024-10-29 06:11:29,111 INFO  [io.deb.ser.big.StreamBigqueryChangeConsumer] (main) Using NoBatchSizeWait to optimize batch size
2024-10-29 13:11:29 debezium-server-bigquery-1  | 2024-10-29 06:11:29,204 DEBUG [io.qua.arc.impl] (main) ArC DI container shut down
2024-10-29 13:11:29 debezium-server-bigquery-1  | 2024-10-29 06:11:29,214 DEBUG [io.qua.ver.cor.run.NoopShutdownExecutorService] (vert.x-eventloop-thread-0) shutdownNow() deliberately not delegated
2024-10-29 13:11:29 debezium-server-bigquery-1  | 2024-10-29 06:11:29,221 DEBUG [io.qua.thread-pool] (main) loop: 1, remaining: 60000000000, intervalRemaining: 5000000000, interruptRemaining: 10000000000
2024-10-29 13:11:29 debezium-server-bigquery-1  | 2024-10-29 06:11:29,226 ERROR [io.qua.run.Application] (main) Failed to start application: java.lang.RuntimeException: Failed to start quarkus
2024-10-29 13:11:29 debezium-server-bigquery-1  |       at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
2024-10-29 13:11:29 debezium-server-bigquery-1  |       at io.quarkus.runtime.Application.start(Application.java:101)
2024-10-29 13:11:29 debezium-server-bigquery-1  |       at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:119)
2024-10-29 13:11:29 debezium-server-bigquery-1  |       at io.quarkus.runtime.Quarkus.run(Quarkus.java:71)
2024-10-29 13:11:29 debezium-server-bigquery-1  |       at io.quarkus.runtime.Quarkus.run(Quarkus.java:44)
2024-10-29 13:11:29 debezium-server-bigquery-1  |       at io.quarkus.runtime.Quarkus.run(Quarkus.java:124)
2024-10-29 13:11:29 debezium-server-bigquery-1  |       at io.debezium.server.Main.main(Main.java:15)
2024-10-29 13:11:29 debezium-server-bigquery-1  | Caused by: java.lang.NoSuchMethodError: 'java.lang.String com.google.cloud.bigquery.BigQueryOptions.getResolvedApiaryHost(java.lang.String)'
2024-10-29 13:11:29 debezium-server-bigquery-1  |       at com.google.cloud.bigquery.spi.v2.HttpBigQueryRpc.<init>(HttpBigQueryRpc.java:110)
2024-10-29 13:11:29 debezium-server-bigquery-1  |       at com.google.cloud.bigquery.BigQueryOptions$DefaultBigQueryRpcFactory.create(BigQueryOptions.java:59)
2024-10-29 13:11:29 debezium-server-bigquery-1  |       at com.google.cloud.bigquery.BigQueryOptions$DefaultBigQueryRpcFactory.create(BigQueryOptions.java:53)
2024-10-29 13:11:29 debezium-server-bigquery-1  |       at com.google.cloud.ServiceOptions.getRpc(ServiceOptions.java:564)
2024-10-29 13:11:29 debezium-server-bigquery-1  |       at com.google.cloud.bigquery.BigQueryOptions.getBigQueryRpcV2(BigQueryOptions.java:128)
2024-10-29 13:11:29 debezium-server-bigquery-1  |       at com.google.cloud.bigquery.BigQueryImpl.<init>(BigQueryImpl.java:257)
2024-10-29 13:11:29 debezium-server-bigquery-1  |       at com.google.cloud.bigquery.BigQueryOptions$DefaultBigQueryFactory.create(BigQueryOptions.java:49)
2024-10-29 13:11:29 debezium-server-bigquery-1  |       at com.google.cloud.bigquery.BigQueryOptions$DefaultBigQueryFactory.create(BigQueryOptions.java:43)
2024-10-29 13:11:29 debezium-server-bigquery-1  |       at com.google.cloud.ServiceOptions.getService(ServiceOptions.java:544)
2024-10-29 13:11:29 debezium-server-bigquery-1  |       at io.debezium.server.bigquery.ConsumerUtil.bigqueryClient(ConsumerUtil.java:116)
2024-10-29 13:11:29 debezium-server-bigquery-1  |       at io.debezium.server.bigquery.StreamBigqueryChangeConsumer.initizalize(StreamBigqueryChangeConsumer.java:118)
2024-10-29 13:11:29 debezium-server-bigquery-1  |       at io.debezium.server.bigquery.StreamBigqueryChangeConsumer.connect(StreamBigqueryChangeConsumer.java:100)
2024-10-29 13:11:29 debezium-server-bigquery-1  |       at io.debezium.server.bigquery.StreamBigqueryChangeConsumer_Bean.doCreate(Unknown Source)
2024-10-29 13:11:29 debezium-server-bigquery-1  |       at io.debezium.server.bigquery.StreamBigqueryChangeConsumer_Bean.create(Unknown Source)
2024-10-29 13:11:29 debezium-server-bigquery-1  |       at io.debezium.server.bigquery.StreamBigqueryChangeConsumer_Bean.create(Unknown Source)
2024-10-29 13:11:29 debezium-server-bigquery-1  |       at io.debezium.server.DebeziumServer.start(DebeziumServer.java:129)
2024-10-29 13:11:29 debezium-server-bigquery-1  |       at io.debezium.server.DebeziumServer_Bean.doCreate(Unknown Source)
2024-10-29 13:11:29 debezium-server-bigquery-1  |       at io.debezium.server.DebeziumServer_Bean.create(Unknown Source)
2024-10-29 13:11:29 debezium-server-bigquery-1  |       at io.debezium.server.DebeziumServer_Bean.create(Unknown Source)
2024-10-29 13:11:29 debezium-server-bigquery-1  |       at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:119)
2024-10-29 13:11:29 debezium-server-bigquery-1  |       at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:38)
2024-10-29 13:11:29 debezium-server-bigquery-1  |       at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:35)
2024-10-29 13:11:29 debezium-server-bigquery-1  |       at io.quarkus.arc.generator.Default_jakarta_enterprise_context_ApplicationScoped_ContextInstances.c1(Unknown Source)
2024-10-29 13:11:29 debezium-server-bigquery-1  |       at io.quarkus.arc.generator.Default_jakarta_enterprise_context_ApplicationScoped_ContextInstances.computeIfAbsent(Unknown Source)
2024-10-29 13:11:29 debezium-server-bigquery-1  |       at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:35)
2024-10-29 13:11:29 debezium-server-bigquery-1  |       at io.quarkus.arc.impl.ClientProxies.getApplicationScopedDelegate(ClientProxies.java:21)
2024-10-29 13:11:29 debezium-server-bigquery-1  |       at io.debezium.server.DebeziumServer_ClientProxy.arc$delegate(Unknown Source)
2024-10-29 13:11:29 debezium-server-bigquery-1  |       at io.debezium.server.DebeziumServer_ClientProxy.arc_contextualInstance(Unknown Source)
2024-10-29 13:11:29 debezium-server-bigquery-1  |       at io.debezium.server.DebeziumServer_Observer_Synthetic_yxbzsjfVdK90Hy855fOO3h4WYv4.notify(Unknown Source)
2024-10-29 13:11:29 debezium-server-bigquery-1  |       at io.quarkus.arc.impl.EventImpl$Notifier.notifyObservers(EventImpl.java:351)
2024-10-29 13:11:29 debezium-server-bigquery-1  |       at io.quarkus.arc.impl.EventImpl$Notifier.notify(EventImpl.java:333)
2024-10-29 13:11:29 debezium-server-bigquery-1  |       at io.quarkus.arc.impl.EventImpl.fire(EventImpl.java:80)
2024-10-29 13:11:29 debezium-server-bigquery-1  |       at io.quarkus.arc.runtime.ArcRecorder.fireLifecycleEvent(ArcRecorder.java:156)
2024-10-29 13:11:29 debezium-server-bigquery-1  |       at io.quarkus.arc.runtime.ArcRecorder.handleLifecycleEvents(ArcRecorder.java:107)
2024-10-29 13:11:29 debezium-server-bigquery-1  |       at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy_0(Unknown Source)
2024-10-29 13:11:29 debezium-server-bigquery-1  |       at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy(Unknown Source)
2024-10-29 13:11:29 debezium-server-bigquery-1  |       ... 7 more
2024-10-29 13:11:29 debezium-server-bigquery-1  | 
2024-10-29 13:11:29 debezium-server-bigquery-1  | 2024-10-29 06:11:29,227 DEBUG [io.qua.run.Application] (main) Stopping application
2024-10-29 13:11:29 debezium-server-bigquery-1  | 2024-10-29 06:11:29,227 DEBUG [io.qua.run.Application] (main) Shutting down with exit code 1
```

config: 

```conf
# ==================== SOURCE DB == POSTGRESQL ====================

debezium.source.connector.class=io.debezium.connector.postgresql.PostgresConnector

debezium.source.database.hostname=postgres-staging
debezium.source.database.port=5432
debezium.source.database.user=user
debezium.source.database.password=xxxxxx
debezium.source.database.dbname=test
debezium.source.database.sslmode=disable

debezium.source.offset.storage=io.debezium.server.bigquery.offset.BigqueryOffsetBackingStore
debezium.source.offset.storage.bigquery.table-name=__dbz_offset
debezium.source.offset.flush.interval.ms=60000

debezium.source.database.history=io.debezium.server.bigquery.history.BigquerySchemaHistory
debezium.source.database.history.bigquery.table-name=__dbz_history

debezium.source.plugin.name=pgoutput
debezium.source.slot.name=slot_dbz_bq_demo
debezium.source.publication.name=db_pub_dbz_bq
debezium.source.publication.autocreate.mode=disabled

# ==================== SINK ====================

# debezium.sink.type=bigquerybatch
# debezium.sink.bigquerybatch.project=kholistest
# debezium.sink.bigquerybatch.dataset=stage_postgresql_test_public
# debezium.sink.bigquerybatch.location=asia-southeast1
# debezium.sink.bigquerybatch.credentials-file=/app/secrets/sa.json

# debezium.sink.bigquerybatch.create-disposition=CREATE_IF_NEEDED
# debezium.sink.bigquerybatch.partition-field=__ts_ms
# debezium.sink.bigquerybatch.clustering-field=__source_ts_ms
# debezium.sink.bigquerybatch.partition-type=DAY
# debezium.sink.bigquerybatch.allow-field-addition=true
# debezium.sink.bigquerybatch.allow-field-relaxation=true
# debezium.sink.bigquerybatch.cast-deleted-field=false

# debezium.sink.batch.batch-size-wait=NoBatchSizeWait

debezium.sink.type=bigquerystream
debezium.sink.bigquerystream.dataset=stage_postgresql_test_public
debezium.sink.bigquerystream.location=asia-southeast1
debezium.sink.bigquerystream.project=kholistest
debezium.sink.bigquerystream.ignore-unknown-fields=false
debezium.sink.bigquerystream.credentials-file=/app/secrets/sa.json

# ==================== TRANSFORMS ====================

debezium.transforms=unwrap
debezium.transforms.unwrap.type=io.debezium.transforms.ExtractNewRecordState
debezium.transforms.unwrap.add.fields=op,table,lsn,source.ts_ms
debezium.transforms.unwrap.add.headers=db
debezium.transforms.unwrap.delete.tombstone.handling.mode=rewrite

# ==================== MISC ====================

debezium.format.value=json
debezium.format.key=json
debezium.format.schemas.enable=true

# ==================== LOG LEVELS ====================
quarkus.log.level=DEBUG
quarkus.log.console.json=false
# Ignore messages below warning level from Jetty, because it's a bit verbose
quarkus.log.category."org.eclipse.jetty".level=WARN

```

any idea how to fix it? any misconfig @ismailsimsek 

or is there any version mismatch in the dependency?

**Comment by ismailsimsek** [comment]
the config looks correct, version mismatch most likely. which version of the application are you using, is this latest release? i will try to reproduce it locally

**Comment by kholisrag** [comment]
@ismailsimsek 

I'm using docker image : 

```
ghcr.io/memiiso/debezium-server-bigquery:0.3.0.Final
```

`docker-compose.yml`

```yaml
services:
  debezium-server-bigquery:
    platform: linux/amd64
    image: ghcr.io/memiiso/debezium-server-bigquery:0.3.0.Final
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8083:8083"
    volumes:
      - ./config:/app/conf
      - ./secrets:/app/secrets

```

**Comment by kholisrag** [comment]
Will try the newest image

**Comment by kholisrag** [comment]
got new error :

```
dbz-bq-server-postgres-staging-lk6-demo-757648f6b4-j5kds dbz-bq-server-postgres-staging-lk6-demo 2024-10-30 02:05:07,868 ERROR [io.deb.ser.ConnectorLifecycle] (pool-7-thread-1) Connector completed: success = 'false', message = 'Connector configuration is not valid. The 'topic.prefix' value is invalid: A value is required', error = 'null'
```

what topic is this? kafka topic? we don't use kafka right? @ismailsimsek please advice, thanks in advance

**Comment by ismailsimsek** [comment]
@kholisrag `topic.prefix` required by debezium. with the consumer its used to prefix the destination tables. 
- bigquery table name ends up like this: `{topic.prefix}_{source_database_name}_{table_name}` as parefix `dbz` could be good one. 

`offset storage naming` issue is solved now. it will be released with the new version son. thank you for reporting it. 

Not sure about the last error message. try to increase the log level to see further details.
Normally the application will try to create the table(with clustering, time partitioning and correct schema) with the first upload. 
- clustering fields are taken from source table primary key field. if PK not available then user provided `clustering-field` value taken. if not provided then `__source_ts_ms` is used for clustering.
  - make sure  __source_ts_ms is generated with the events/flattening.
- by default partition field is" `__source_ts_ms`, with `MONTH` level partitioned. unless user provides different setting.
```
quarkus.log.category."io.debezium.server.bigquery".level=INFO
quarkus.log.category."com.google.cloud.bigquery".level=DEBUG
```

**Comment by ismailsimsek** [comment]
since your setting uses this two fields. 
```
debezium.sink.bigquerybatch.partition-field=__ts_ms
debezium.sink.bigquerybatch.clustering-field=__source_ts_ms
```

i believe the flattening config should be
```
#current# debezium.transforms.unwrap.add.fields=op,table,lsn,source.ts_ms
debezium.transforms.unwrap.add.fields=op,table,lsn,source.ts_ms,ts_ms
```

**Comment by kholisrag** [comment]
Thank You! All Clear now!
