### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by vapdl** [memiiso/debezium-server-bigquery#63]
Hi, could you please help me to find why this error is happening?

2023-01-24 19:01:59,152 INFO  [io.deb.con.mys.MySqlStreamingChangeEventSource] (blc-aedwh.public.adenviesandbox.com:25060) Stopped reading binlog after 0 events, last recorded offset: {transaction_id=null, ts_sec=1674601317, file=binlog.000321, pos=0, server_id=1, event=1}
2023-01-24 19:01:59,254 INFO  [io.deb.jdb.JdbcConnection] (pool-11-thread-1) Connection gracefully closed
2023-01-24 19:01:59,255 INFO  [org.apa.kaf.con.sto.FileOffsetBackingStore] (pool-7-thread-1) Stopped FileOffsetBackingStore
2023-01-24 19:01:59,255 INFO  [io.deb.ser.ConnectorLifecycle] (pool-7-thread-1) Connector completed: success = 'false', message = 'Stopping connector after error in the application's handler method: null', error = '{}': java.lang.NullPointerException
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:889)
        at com.google.cloud.bigquery.Field.<init>(Field.java:296)
        at com.google.cloud.bigquery.Field.<init>(Field.java:37)
        at com.google.cloud.bigquery.Field$Builder.build(Field.java:290)
        at com.google.cloud.bigquery.Field.of(Field.java:407)
        at io.debezium.server.bigquery.DebeziumBigqueryEvent.getPrimitiveField(DebeziumBigqueryEvent.java:184)
        at io.debezium.server.bigquery.DebeziumBigqueryEvent.getBigQuerySchemaFields(DebeziumBigqueryEvent.java:112)
        at io.debezium.server.bigquery.DebeziumBigqueryEvent.getBigQuerySchema(DebeziumBigqueryEvent.java:338)
        at io.debezium.server.bigquery.StreamBigqueryChangeConsumer.getTable(StreamBigqueryChangeConsumer.java:201)
        at io.debezium.server.bigquery.StreamBigqueryChangeConsumer.uploadDestination(StreamBigqueryChangeConsumer.java:176)
        at io.debezium.server.bigquery.AbstractChangeConsumer.handleBatch(AbstractChangeConsumer.java:127)
        at io.debezium.embedded.ConvertingEngineBuilder.lambda$notifying$2(ConvertingEngineBuilder.java:83)
        at io.debezium.embedded.EmbeddedEngine.run(EmbeddedEngine.java:822)
        at io.debezium.embedded.ConvertingEngineBuilder$2.run(ConvertingEngineBuilder.java:192)
        at io.debezium.server.DebeziumServer.lambda$start$1(DebeziumServer.java:152)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)

2023-01-24 19:01:59,263 INFO  [io.deb.ser.DebeziumServer] (main) Received request to stop the engine
2023-01-24 19:01:59,263 INFO  [io.deb.emb.EmbeddedEngine] (main) Stopping the embedded engine
2023-01-24 19:01:59,280 INFO  [io.quarkus] (main) debezium-server-bigquery-dist stopped in 0.024s

here my application.properties

# ==================== SINK ====================

debezium.sink.type=bigquerystream
debezium.sink.bigquerystream.project=devsdsdsdce
debezium.sink.bigquerystream.dataset=test
debezium.sink.bigquerystream.location=eu
debezium.sink.bigquerystream.credentials-file=/home/vapdl/BQ_DEV.json
debezium.sink.bigquerystream.create-if-needed=true
debezium.sink.bigquerystream.ignore-unknown-fields=true

**Comment by ismailsimsek** [comment]
@vapdl could it be that the destination table is crated but not yet available to load data into. 
`bigquerystream` consumer creates tables automatically but it takes time for the table to be available for streaming data into.

maybe start debezium after all the destination(BQ) tables are created

**Comment by vapdl** [comment]
perfect. You're correct @ismailsimsek thanks!
